.PHONY: clean All

All:
	@echo "----------Building project:[ 00_LinkedList - Debug ]----------"
	@cd "00_LinkedList" && "$(MAKE)" -f  "00_LinkedList.mk"
clean:
	@echo "----------Cleaning project:[ 00_LinkedList - Debug ]----------"
	@cd "00_LinkedList" && "$(MAKE)" -f  "00_LinkedList.mk" clean
