.PHONY: clean All

All:
	@echo "----------Building project:[ StringTask - Debug ]----------"
	@cd "StringTask" && "$(MAKE)" -f  "StringTask.mk"
clean:
	@echo "----------Cleaning project:[ StringTask - Debug ]----------"
	@cd "StringTask" && "$(MAKE)" -f  "StringTask.mk" clean
