.PHONY: clean All

All:
	@echo "----------Building project:[ 04_BinarySearch - Debug ]----------"
	@cd "04_BinarySearch" && "$(MAKE)" -f  "04_BinarySearch.mk"
clean:
	@echo "----------Cleaning project:[ 04_BinarySearch - Debug ]----------"
	@cd "04_BinarySearch" && "$(MAKE)" -f  "04_BinarySearch.mk" clean
