.PHONY: clean All

All:
	@echo "----------Building project:[ 6_RotateArray - Debug ]----------"
	@cd "6_RotateArray" && "$(MAKE)" -f  "6_RotateArray.mk"
clean:
	@echo "----------Cleaning project:[ 6_RotateArray - Debug ]----------"
	@cd "6_RotateArray" && "$(MAKE)" -f  "6_RotateArray.mk" clean
