.PHONY: clean All

All:
	@echo "----------Building project:[ 8_VectorImplementation - Debug ]----------"
	@cd "8_VectorImplementation" && "$(MAKE)" -f  "8_VectorImplementation.mk"
clean:
	@echo "----------Cleaning project:[ 8_VectorImplementation - Debug ]----------"
	@cd "8_VectorImplementation" && "$(MAKE)" -f  "8_VectorImplementation.mk" clean
