.PHONY: clean All

All:
	@echo "----------Building project:[ _10_ClosestNumber - Debug ]----------"
	@cd "10_ClosestNumber" && "$(MAKE)" -f  "_10_ClosestNumber.mk"
clean:
	@echo "----------Cleaning project:[ _10_ClosestNumber - Debug ]----------"
	@cd "10_ClosestNumber" && "$(MAKE)" -f  "_10_ClosestNumber.mk" clean
