.PHONY: clean All

All:
	@echo "----------Building project:[ Google1 - Debug ]----------"
	@cd "Google1" && "$(MAKE)" -f  "Google1.mk"
clean:
	@echo "----------Cleaning project:[ Google1 - Debug ]----------"
	@cd "Google1" && "$(MAKE)" -f  "Google1.mk" clean
